---
- name: copy files from tower to client
  hosts: all
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /tmp/test.txt
      dest: /tmp/copytest.txt
      remote_src: yes  # Tells Ansible the file is on the remote machine
      owner: root
      group: root
      mode: '0644'
